/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/(main)': RouteRecordInfo<
      '/(main)',
      '/',
      Record<never, never>,
      Record<never, never>,
      | '/(main)/dashboard/default'
      | '/(main)/doctors/add'
      | '/(main)/doctors/edit'
      | '/(main)/doctors/list'
      | '/(main)/doctors/profile'
      | '/(main)/hospitals/[hospital_id]/contract'
      | '/(main)/hospitals/[hospital_id]/dashboard'
      | '/(main)/hospitals/[hospital_id]/department'
      | '/(main)/hospitals/[hospital_id]/menu'
      | '/(main)/hospitals/[hospital_id]/patient'
      | '/(main)/hospitals/add'
      | '/(main)/hospitals/edit'
      | '/(main)/hospitals/list'
      | '/(main)/starter'
    >,
    '/(main)/dashboard/default': RouteRecordInfo<
      '/(main)/dashboard/default',
      '/dashboard/default',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/doctors/add': RouteRecordInfo<
      '/(main)/doctors/add',
      '/doctors/add',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/doctors/edit': RouteRecordInfo<
      '/(main)/doctors/edit',
      '/doctors/edit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/doctors/list': RouteRecordInfo<
      '/(main)/doctors/list',
      '/doctors/list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/doctors/profile': RouteRecordInfo<
      '/(main)/doctors/profile',
      '/doctors/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/hospitals/[hospital_id]/contract': RouteRecordInfo<
      '/(main)/hospitals/[hospital_id]/contract',
      '/hospitals/:hospital_id/contract',
      { hospital_id: ParamValue<true> },
      { hospital_id: ParamValue<false> },
      | never
    >,
    '/(main)/hospitals/[hospital_id]/dashboard': RouteRecordInfo<
      '/(main)/hospitals/[hospital_id]/dashboard',
      '/hospitals/:hospital_id/dashboard',
      { hospital_id: ParamValue<true> },
      { hospital_id: ParamValue<false> },
      | never
    >,
    '/(main)/hospitals/[hospital_id]/department': RouteRecordInfo<
      '/(main)/hospitals/[hospital_id]/department',
      '/hospitals/:hospital_id/department',
      { hospital_id: ParamValue<true> },
      { hospital_id: ParamValue<false> },
      | never
    >,
    '/(main)/hospitals/[hospital_id]/menu': RouteRecordInfo<
      '/(main)/hospitals/[hospital_id]/menu',
      '/hospitals/:hospital_id/menu',
      { hospital_id: ParamValue<true> },
      { hospital_id: ParamValue<false> },
      | never
    >,
    '/(main)/hospitals/[hospital_id]/patient': RouteRecordInfo<
      '/(main)/hospitals/[hospital_id]/patient',
      '/hospitals/:hospital_id/patient',
      { hospital_id: ParamValue<true> },
      { hospital_id: ParamValue<false> },
      | never
    >,
    '/(main)/hospitals/add': RouteRecordInfo<
      '/(main)/hospitals/add',
      '/hospitals/add',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/hospitals/edit': RouteRecordInfo<
      '/(main)/hospitals/edit',
      '/hospitals/edit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/hospitals/list': RouteRecordInfo<
      '/(main)/hospitals/list',
      '/hospitals/list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(main)/starter': RouteRecordInfo<
      '/(main)/starter',
      '/starter',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/maintenance/error': RouteRecordInfo<
      '/maintenance/error',
      '/maintenance/error',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(main).vue': {
      routes:
        | '/(main)'
        | '/(main)/dashboard/default'
        | '/(main)/doctors/add'
        | '/(main)/doctors/edit'
        | '/(main)/doctors/list'
        | '/(main)/doctors/profile'
        | '/(main)/hospitals/[hospital_id]/contract'
        | '/(main)/hospitals/[hospital_id]/dashboard'
        | '/(main)/hospitals/[hospital_id]/department'
        | '/(main)/hospitals/[hospital_id]/menu'
        | '/(main)/hospitals/[hospital_id]/patient'
        | '/(main)/hospitals/add'
        | '/(main)/hospitals/edit'
        | '/(main)/hospitals/list'
        | '/(main)/starter'
      views:
        | 'default'
    }
    'src/pages/(main)/dashboard/default.vue': {
      routes:
        | '/(main)/dashboard/default'
      views:
        | never
    }
    'src/pages/(main)/doctors/add.vue': {
      routes:
        | '/(main)/doctors/add'
      views:
        | never
    }
    'src/pages/(main)/doctors/edit.vue': {
      routes:
        | '/(main)/doctors/edit'
      views:
        | never
    }
    'src/pages/(main)/doctors/list.vue': {
      routes:
        | '/(main)/doctors/list'
      views:
        | never
    }
    'src/pages/(main)/doctors/profile.vue': {
      routes:
        | '/(main)/doctors/profile'
      views:
        | never
    }
    'src/pages/(main)/hospitals/[hospital_id]/contract.vue': {
      routes:
        | '/(main)/hospitals/[hospital_id]/contract'
      views:
        | never
    }
    'src/pages/(main)/hospitals/[hospital_id]/dashboard.vue': {
      routes:
        | '/(main)/hospitals/[hospital_id]/dashboard'
      views:
        | never
    }
    'src/pages/(main)/hospitals/[hospital_id]/department.vue': {
      routes:
        | '/(main)/hospitals/[hospital_id]/department'
      views:
        | never
    }
    'src/pages/(main)/hospitals/[hospital_id]/menu.vue': {
      routes:
        | '/(main)/hospitals/[hospital_id]/menu'
      views:
        | never
    }
    'src/pages/(main)/hospitals/[hospital_id]/patient.vue': {
      routes:
        | '/(main)/hospitals/[hospital_id]/patient'
      views:
        | never
    }
    'src/pages/(main)/hospitals/add.vue': {
      routes:
        | '/(main)/hospitals/add'
      views:
        | never
    }
    'src/pages/(main)/hospitals/edit.vue': {
      routes:
        | '/(main)/hospitals/edit'
      views:
        | never
    }
    'src/pages/(main)/hospitals/list.vue': {
      routes:
        | '/(main)/hospitals/list'
      views:
        | never
    }
    'src/pages/(main)/starter.vue': {
      routes:
        | '/(main)/starter'
      views:
        | never
    }
    'src/pages/maintenance/error.vue': {
      routes:
        | '/maintenance/error'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
